# Generated by Django 5.2.4 on 2025-12-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('student', 'Student'), ('employee', 'Employee')], max_length=20)),
                ('specialization', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='student',
            name='specialization',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
